UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/halifax/profile/plumber/pace-plumbing-heating-ltd-0087-4301', is_verified = TRUE WHERE name = 'Pace Plumbing & Heating Ltd';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/halifax/profile/heating-contractors/david-canning-heat-maintenance-0087-23257', is_verified = TRUE WHERE name = 'David Canning Heat & Maintenance';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/halifax/profile/plumber/dimitris-plumbing-heating-limited-0087-42693', is_verified = TRUE WHERE name = 'Dimitri''s Plumbing & Heating Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/halifax/profile/general-contractor/gil-son-construction-limited-0087-37985', is_verified = TRUE WHERE name = 'Gil-Son Construction Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/halifax/profile/plumber/bremners-plumbing-heating-ltd-0087-703', is_verified = TRUE WHERE name = 'Bremner''s Plumbing & Heating Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/plumbing-and-heating/mackenzie-professional-plumbing-heating-inc-0087-88408', is_verified = TRUE WHERE name = 'MacKenzie Professional Plumbing & Heating Inc.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/heating-and-air-conditioning/maritime-hvac-0087-70880', is_verified = TRUE WHERE name = 'Maritime HVAC';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/general-contractor/carverys-construction-limited-0087-24346', is_verified = TRUE WHERE name = 'Carvery''s Construction Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/plumbing-and-heating/pothier-plumbing-and-heating-inc-0087-69819', is_verified = TRUE WHERE name = 'Pothier Plumbing and Heating Inc.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/commercial-contractors/ryson-construction-0087-25465', is_verified = TRUE WHERE name = 'Ryson Construction';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/general-contractor/jim-kimber-construction-0087-37958', is_verified = TRUE WHERE name = 'Jim Kimber Construction';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/plumbing-and-heating/gopher-plumbing-hydronic-heating-inc-0087-90005', is_verified = TRUE WHERE name = 'Gopher Plumbing & Hydronic Heating Inc.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/plumbing-and-heating/roski-mechanical-0087-90465', is_verified = TRUE WHERE name = 'Roski Mechanical';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/plumber/ken-evans-plumbing-heating-ltd-0087-909', is_verified = TRUE WHERE name = 'Ken Evans Plumbing & Heating Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/eastern-passage/profile/plumber/dartmouth-central-plumbing-heating-ltd-0087-25036', is_verified = TRUE WHERE name = 'Dartmouth Central Plumbing & Heating Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/bedford/profile/plumber/master-tech-hvac-and-plumbing-0087-9062', is_verified = TRUE WHERE name = 'Master Tech HVAC and Plumbing';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/dartmouth/profile/home-repair/sir-fix-a-lot-inc-0087-89732', is_verified = TRUE WHERE name = 'Sir Fix A Lot Inc.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/westphal/profile/plumbing-and-heating/amacs-plumbing-and-heating--0087-90957', is_verified = TRUE WHERE name = 'AMACS Plumbing and Heating';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/hammonds-plains/profile/plumbing-and-heating/joes-plumbing-heating-and-air-conditioning-ltd-0087-72261', is_verified = TRUE WHERE name = 'Joe''s Plumbing, Heating and Air Conditioning Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/portuguese-cove/profile/plumber/beavs-plumbing-heating-limited-0087-18951', is_verified = TRUE WHERE name = 'Beav''s Plumbing & Heating Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/upper-tantallon/profile/plumber/accent-plumbing-heating-ltd-0087-20009', is_verified = TRUE WHERE name = 'Accent Plumbing & Heating Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/halifax/profile/plumber/jeffries-plumbing-ltd-0087-86003', is_verified = TRUE WHERE name = 'Jeffries Plumbing Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/fletchers-lake/profile/plumber/lee-castle-plumbing-ltd-0087-18024', is_verified = TRUE WHERE name = 'Lee Castle Plumbing Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/head-of-saint-margarets-bay/profile/mechanical-contractors/alltime-mechanical-ltd-0087-74409', is_verified = TRUE WHERE name = 'AllTime Mechanical Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/mount-uniacke/profile/plumber/garys-plumbing-heating-ltd-0087-25014', is_verified = TRUE WHERE name = 'Gary''s Plumbing & Heating Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/pine-grove/profile/home-renovation/d-s-renovations-0087-47870', is_verified = TRUE WHERE name = 'D & S Renovations';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/mount-uniacke/profile/plumbing-and-heating/macgregor-brown-plumbing-heating-0087-89938', is_verified = TRUE WHERE name = 'MacGregor Brown Plumbing & Heating';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/bridgewater/profile/home-builders/millennium-residential-construction-inc-0087-27039', is_verified = TRUE WHERE name = 'Millennium Residential Construction Inc.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/greenfield/profile/plumber/zmp-plumbing-and-excavation-0087-82532', is_verified = TRUE WHERE name = 'ZMP Plumbing and Excavation';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/cambridge/profile/plumber/gc-baxter-plumbing-heating-limited-0087-332', is_verified = TRUE WHERE name = 'G.C. Baxter Plumbing & Heating Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/canning/profile/plumber/true-flush-plumbing-and-heating--0087-45082', is_verified = TRUE WHERE name = 'True Flush Plumbing and Heating';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/berwick/profile/plumber/palmer-plumbing-and-heating-ltd-0087-31998', is_verified = TRUE WHERE name = 'Palmer Plumbing and Heating Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/westville/profile/plumber/tnb-plumbing-heating-air-conditioning-ltd-0087-30012', is_verified = TRUE WHERE name = 'TNB Plumbing Heating Air Conditioning Ltd';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/river-john/profile/electrician/rh-winmill-electric-ltd-0087-3398', is_verified = TRUE WHERE name = 'R.H. Winmill Electric Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/antigonish/profile/plumber/ian-j-tate-plumbing-heating-limited-0087-41462', is_verified = TRUE WHERE name = 'Ian J. Tate Plumbing & Heating Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/st-andrews/profile/plumber/ian-j-tate-plumbing-heating-limited-0087-41462/addressId/40467', is_verified = TRUE WHERE name = 'Ian J. Tate Plumbing & Heating Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/digby-co/profile/electrician/j-d-electrical-plumbing-limited-0087-17114', is_verified = TRUE WHERE name = 'J & D Electrical & Plumbing Limited';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/yarmouth/profile/electrician/graves-electrical-ltd-0087-18319', is_verified = TRUE WHERE name = 'Graves Electrical Ltd.';
UPDATE businesses SET is_bbb_accredited = TRUE, bbb_url = 'https://www.bbb.org/ca/ns/yarmouth/profile/electrician/graves-electrical-ltd-0087-18319/addressId/2906', is_verified = TRUE WHERE name = 'Graves Electrical Ltd.';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Ignite Energy Atlantic';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'R H Winmill Electric Limited';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'W McNeil Electrical Contracting';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Tony Rhynold Electrical, Plumbing & Heating Ltd.';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Aim Electrical and Plumbing Services';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'White Rock Mechanical Services';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Magliaro Plumbing & Heating LTD';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'PR General Contractors Inc.';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Evergreen Electric Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'First Choice Sewer Inspection and Drain Cleaning Limited';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Graves Electrical Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Ready Refrigeration Inc.';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Corkum''s Electrical Sales & Service Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Metro Commercial Heating and Cooling Limited';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Rhyno''s Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'JJ''s Heat Pump and Electric';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Scotia Mechanical Solutions';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'White Rock Mechanical Services';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Ignite Energy Atlantic';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'MacLaren Appliance Repair & Refrigeration Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Nova Dry Basement Systems 2024 Limited';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'EMCO Corporation';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Geddes & Murphy Electric Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Halls Heating Air Conditioning & Maintenance Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'WB Electrical Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'High Island Electric';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'L&B Electric Ltd.';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Len''s Plumbing & Heating Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'W McNeil Electrical Contracting';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Pankhurst Electric Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Brian G. Inglis Consulting';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Master Tech HVAC & Plumbing Inc';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'Rexel Atlantic';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'J W Bird and Company Ltd';
UPDATE businesses SET is_efficiency_ns_partner = TRUE WHERE name = 'R H Winmill Electric Limited';
